[package]
name = "tpntree"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "0.22"
nalgebra = { version = "0.28", optional = true }

[features]
default = ["nalgebra"]
